name: Image
on:
  push:
    tags:
      - "v*"
jobs:
  image:
    name: Build and Push Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Install bpftool and compiler collection
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm linux-headers-$(uname -r) libbpf-dev
      - name: Generate vmlinux.h
        run: |
          docker run --rm ghcr.io/terassyi/bpf-utils:0.1.1 bpftool btf dump file /sys/kernel/btf/vmlinux format c > bpf/include/vmlinux.h
      - name: Build bpf program
        run: |
          make build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Tag
        id: set-tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT # Remove "v" prefix.
      - name: Build and Push msq-obsrv
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/terassyi/msq-obsrv:${{ steps.set-tag.outputs.RELEASE_TAG }}
